[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npx tsc",
  "npx prisma db push"
]

[start]
cmd = "node simple-railway-start.js"
