[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "cp prisma/schema.railway.prisma prisma/schema.prisma",
  "npx prisma generate --schema=./prisma/schema.prisma",
  "npx tsc",
  "npx prisma db push --schema=./prisma/schema.prisma"
]

[start]
cmd = "node simple-railway-start.js"
